# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25505deffb0793397124712496b964941e58b796266f8880e7db68d22fb3dfc22c3e659f48e5e065b26202ae5e1cf21a9a31c8b6fe6477ced4b8872788841556

test:
  secret_key_base: 3c731d7e2130418b9a771b4542b1ebbf830052dbeeb3b7ef36b5a8de82f3bd5fce905e321566ad4a07d8565c6ae9a273aff254ffb4c1bea0f59f9d22770ae3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
